/**
 * Hub instrument list — titles match folder slugs (Title Case).
 */
export const HUB_APPS = [
  {
    href: "apps/conductor/",
    title: "Conductor",
    section: "rhythm",
    synth: "Ensemble click",
    sensors: "Touch · shared URL",
  },
  {
    href: "apps/part/",
    title: "Part",
    section: "rhythm",
    synth: "Routing only",
    sensors: "QR · touch",
  },
  {
    href: "apps/drumkit/",
    title: "Drumkit",
    section: "rhythm",
    synth: "Drum synthesis",
    sensors: "Touch",
  },
  {
    href: "apps/drum-sequencer/",
    title: "Drum Sequencer",
    section: "rhythm",
    synth: "Step sequencer",
    sensors: "Touch",
  },
  {
    href: "apps/circular-drum/",
    title: "Circular Drum",
    section: "rhythm",
    synth: "Ring sequencer",
    sensors: "Touch",
  },
  {
    href: "apps/firefly/",
    title: "Firefly",
    section: "rhythm",
    synth: "Pulse click",
    sensors: "Mic · touch",
  },
  {
    href: "apps/delay-throw/",
    title: "Delay Throw",
    section: "rhythm",
    synth: "Delay feedback",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/evo-drumkit/",
    title: "Evo Drumkit",
    section: "ai",
    synth: "Evolving drums",
    sensors: "Touch · mic",
  },
  {
    href: "apps/green-button/",
    title: "Green Button",
    section: "drones",
    synth: "Swarm tones",
    sensors: "Touch · motion",
  },
  {
    href: "apps/just-equal/",
    title: "Just Equal",
    section: "drones",
    synth: "Detuned sines",
    sensors: "Touch",
  },
  {
    href: "apps/sound-saber/",
    title: "Sound Saber",
    section: "drones",
    synth: "Pulse · delay · ring",
    sensors: "Touch · motion",
  },
  {
    href: "apps/motion-wah/",
    title: "Motion Trump",
    section: "drones",
    synth: "Bandpass wah",
    sensors: "Touch · motion",
  },
  {
    href: "apps/compass-wah/",
    title: "Compass Wah",
    section: "drones",
    synth: "Compass filter",
    sensors: "Touch · compass · tilt",
  },
  {
    href: "apps/harmonizer/",
    title: "Harmonizer",
    section: "drones",
    synth: "Chroma drones",
    sensors: "Mic · touch",
  },
  {
    href: "apps/piano/",
    title: "Piano",
    section: "melody",
    synth: "Keyboard tones",
    sensors: "Touch",
  },
  {
    href: "apps/synth-pad/",
    title: "Synth Pad",
    section: "melody",
    synth: "Subtractive pad",
    sensors: "Touch",
  },
  {
    href: "apps/mic-theremin/",
    title: "Mic Theremin",
    section: "melody",
    synth: "Pitch-tracked sine",
    sensors: "Mic · touch",
  },
  {
    href: "apps/flute-blow/",
    title: "Flute Blow",
    section: "melody",
    synth: "Breath tone",
    sensors: "Mic · touch",
  },
  {
    href: "apps/tilt-harp/",
    title: "Tilt Harp",
    section: "melody",
    synth: "Plucked harp",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/bow-phone/",
    title: "Bow Phone",
    section: "melody",
    synth: "Bowed string",
    sensors: "Touch · camera",
  },
  {
    href: "apps/fm-touch/",
    title: "FM Touch",
    section: "synthesis",
    synth: "2-op FM · finger or tilt",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/fm-matrix/",
    title: "FM Matrix",
    section: "synthesis",
    synth: "FM matrix",
    sensors: "Touch",
  },
  {
    href: "apps/ks-string/",
    title: "KS String",
    section: "synthesis",
    synth: "KS · stage or pocket",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/additive-bells/",
    title: "Additive Bells",
    section: "synthesis",
    synth: "Additive partials",
    sensors: "Touch · motion",
  },
  {
    href: "apps/filter-ladder/",
    title: "Filter Ladder",
    section: "synthesis",
    synth: "Ladder lowpass",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/ring-mod-gong/",
    title: "Ring Mod Gong",
    section: "synthesis",
    synth: "Ring modulation",
    sensors: "Touch",
  },
  {
    href: "apps/sampler/",
    title: "Sampler",
    section: "texture",
    synth: "Sample playback",
    sensors: "Mic · touch · tilt",
  },
  {
    href: "apps/granular-tilt/",
    title: "Granular Tilt",
    section: "texture",
    synth: "Granular cloud",
    sensors: "Touch · tilt · mic",
  },
  {
    href: "apps/spectral-freeze/",
    title: "Spectral Freeze",
    section: "texture",
    synth: "FFT partials",
    sensors: "Mic · touch",
  },
  {
    href: "apps/tap-bloom/",
    title: "Tap Bloom",
    section: "texture",
    synth: "Generative blooms",
    sensors: "Touch",
  },
  {
    href: "apps/wavetable-scan/",
    title: "Wavetable Scan",
    section: "texture",
    synth: "Wavetable morph",
    sensors: "Touch",
  },
  {
    href: "apps/video-sonifier/",
    title: "Video Sonifier",
    section: "texture",
    synth: "Camera → sound",
    sensors: "Camera",
  },
  {
    href: "apps/hum-clap/",
    title: "Hum Clap",
    section: "ai",
    synth: "k-NN classifier",
    sensors: "Mic",
  },
  {
    href: "apps/train-shake/",
    title: "Train Shake",
    section: "ai",
    synth: "ML gesture map",
    sensors: "Motion",
  },
  {
    href: "apps/markov-melody/",
    title: "Markov Melody",
    section: "melody",
    synth: "2nd-order Markov",
    sensors: "Touch · keyboard",
  },
  {
    href: "apps/euclidean-rings/",
    title: "Euclidean Rings",
    section: "rhythm",
    synth: "Euclidean rings",
    sensors: "Touch",
  },
  {
    href: "apps/lsystem-groove/",
    title: "L-System Groove",
    section: "rhythm",
    synth: "L-system rewrite",
    sensors: "Touch",
  },
  {
    href: "apps/chaos-attractor/",
    title: "Chaos Attractor",
    section: "texture",
    synth: "Chaotic subtractive",
    sensors: "Touch · motion",
  },
  {
    href: "apps/shepard-glide/",
    title: "Shepard Glide",
    section: "drones",
    synth: "Shepard tone",
    sensors: "Touch · tilt",
  },
  { href: "apps/pocket-metronome/", title: "Pocket Metronome", section: "rhythm", synth: "Pulse + duck", sensors: "Accel · touch" },
  { href: "apps/tilt-doppler/", title: "Tilt Doppler", section: "melody", synth: "Pitch glide", sensors: "Tilt · touch" },
  { href: "apps/room-reverb-send/", title: "Room Reverb Send", section: "texture", synth: "Convolver wet", sensors: "Mic · touch" },
  { href: "apps/whisper-gate/", title: "Whisper Gate", section: "texture", synth: "Formant noise", sensors: "Mic · touch" },
  { href: "apps/clap-architect/", title: "Clap Architect", section: "rhythm", synth: "Learned kit", sensors: "Mic · touch" },
  { href: "apps/pitch-hive/", title: "Pitch Hive", section: "drones", synth: "Additive chord", sensors: "Mic · touch" },
  { href: "apps/shake-filter/", title: "Shake Filter", section: "drones", synth: "Subtractive", sensors: "Motion · touch" },
  { href: "apps/flat-edge/", title: "Flat Edge", section: "drones", synth: "Gated drone", sensors: "Tilt · touch" },
  { href: "apps/heading-choir/", title: "Heading Choir", section: "drones", synth: "Detuned pans", sensors: "Compass · touch" },
  { href: "apps/shadow-sequencer/", title: "Shadow Sequencer", section: "rhythm", synth: "8-step mask", sensors: "Camera · touch" },
  { href: "apps/torch-pulse/", title: "Torch Pulse", section: "rhythm", synth: "Click + flash", sensors: "Camera · touch" },
  { href: "apps/pinch-bass/", title: "Pinch Bass", section: "synthesis", synth: "Subtractive bass", sensors: "Pinch · XY" },
  { href: "apps/edge-strum/", title: "Edge Strum", section: "synthesis", synth: "KS harmonics", sensors: "Touch position" },
  { href: "apps/am-radio/", title: "Am Radio", section: "synthesis", synth: "AM sidebands", sensors: "Mic · touch" },
  { href: "apps/phase-distortion/", title: "Phase Distortion", section: "synthesis", synth: "Phase distortion", sensors: "Multi-touch" },
  { href: "apps/supersaw-stack/", title: "Supersaw Stack", section: "synthesis", synth: "Saws or spin timbre", sensors: "Gyro · touch" },
  { href: "apps/bowed-waveguide/", title: "Bowed Waveguide", section: "melody", synth: "Continuous KS", sensors: "Touch drag" },
  { href: "apps/pluck-bowl/", title: "Pluck Bowl", section: "synthesis", synth: "Resonant burst", sensors: "Touch position" },
  { href: "apps/wind-bottle/", title: "Wind Bottle", section: "texture", synth: "Noise resonator", sensors: "Tilt · touch" },
  { href: "apps/scrub-tape/", title: "Scrub Tape", section: "texture", synth: "Buffer scrub", sensors: "Touch drag" },
  { href: "apps/vocoder-choir/", title: "Vocoder Choir", section: "texture", synth: "Band vocoder", sensors: "Mic · tilt" },
  { href: "apps/one-shot-orchestra/", title: "One Shot Orchestra", section: "rhythm", synth: "Multi-zone", sensors: "Touch zones" },
  { href: "apps/gesture-regression/", title: "Gesture Regression", section: "ai", synth: "ML → filter", sensors: "Motion · touch" },
  {
    href: "apps/swarm-bloom/",
    title: "Swarm Bloom",
    section: "drones",
    synth: "Evo drones + rhythm",
    sensors: "Mic · ensemble",
  },
];

/** @param {string} href e.g. "apps/piano/" */
export function catalogEntryForHref(href) {
  return HUB_APPS.find((a) => a.href === href);
}

/** Folder slug from href: "piano" */
export function slugFromHref(href) {
  const m = href.match(/apps\/([^/]+)\//);
  return m ? m[1] : "";
}

/** Title Case display name from folder slug: "bow-phone" → "Bow Phone" */
export function slugToTitle(slug) {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
